name: Sync Kong Configuration

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install DecK
        run: |
          curl -sL https://github.com/kong/deck/releases/download/v1.39.2/deck_1.39.2_linux_amd64.tar.gz -o deck.tar.gz
          tar -xf deck.tar.gz -C /tmp
          cp /tmp/deck /usr/local/bin/

      - name: Backup Configuration for Green Team
        run: |
          if [ -f green-team/green-team-backup.yaml ]; then
            rm green-team/green-team-backup.yaml
          fi
          deck gateway dump --konnect-token $KONNECT_TOKEN --konnect-control-plane-name green-team -o green-team/green-team-backup.yaml
        env:
          KONNECT_TOKEN: ${{ secrets.KONNECT_TOKEN }}

      - name: Upload Backup Artifact for Green Team
        uses: actions/upload-artifact@v3
        with:
          name: green-team-backup
          path: green-team/green-team-backup.yaml

      - name: Backup Configuration for Blue Team
        run: |
          if [ -f blue-team/blue-team-backup.yaml ]; then
            rm blue-team/blue-team-backup.yaml
          fi
          deck gateway dump --konnect-token $KONNECT_TOKEN --konnect-control-plane-name blue-team -o blue-team/blue-team-backup.yaml
        env:
          KONNECT_TOKEN: ${{ secrets.KONNECT_TOKEN }}

      - name: Upload Backup Artifact for Blue Team
        uses: actions/upload-artifact@v3
        with:
          name: blue-team-backup
          path: blue-team/blue-team-backup.yaml

      - name: Sync Configuration to Konnect for Green Team
        run: |
          deck gateway sync --konnect-token $KONNECT_TOKEN --konnect-control-plane-name green-team green-team/green-team.yaml
        env:
          KONNECT_TOKEN: ${{ secrets.KONNECT_TOKEN }}

      - name: Sync Configuration to Konnect for Blue Team
        run: |
          deck gateway sync --konnect-token $KONNECT_TOKEN --konnect-control-plane-name blue-team blue-team/blue-team.yaml
        env:
          KONNECT_TOKEN: ${{ secrets.KONNECT_TOKEN }}