name: Sync Kong Configuration

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure the workflow has permission to write to the repository

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install DecK
        run: |
          curl -sL https://github.com/kong/deck/releases/download/v1.39.2/deck_1.39.2_linux_amd64.tar.gz -o deck.tar.gz
          tar -xf deck.tar.gz -C /tmp
          cp /tmp/deck /usr/local/bin/

      - name: Backup Configuration for Green Team
        run: |
          deck gateway dump --yes --konnect-token $KONNECT_TOKEN --konnect-control-plane-name green-team -o green-team/green-team-backup.yaml
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add green-team/green-team-backup.yaml
          git commit -m "Backup configuration for Green Team"
          git push
        env:
          KONNECT_TOKEN: ${{ secrets.KONNECT_TOKEN }}

      - name: Sync Configuration to Konnect for Green Team
        run: |
          deck gateway sync --konnect-token $KONNECT_TOKEN --konnect-control-plane-name green-team green-team/green-team.yaml
        env:
          KONNECT_TOKEN: ${{ secrets.KONNECT_TOKEN }}